
export type Article = {
  slug: string;
  title: string;
  description: string;
  category: string;
  publishedDate: string;
};

export const articles: Article[] = [
  {
    slug: 'your-complete-guide-to-age-calculators',
    title: 'Your Complete Guide to Age Calculator Hub',
    description: 'Explore our all-in-one age calculator app. From chronological and biological age to pet age and retirement planning, find the perfect tool for every need in our comprehensive guide.',
    category: 'Guides',
    publishedDate: '2024-10-20',
  },
  {
    slug: 'what-is-biological-age-and-how-to-improve-it',
    title: 'The Ultimate Guide to Your Biological Age: Are You Younger or Older Than You Think?',
    description: 'A comprehensive guide to understanding what biological age is, how it\'s measured, and the actionable steps you can take to lower it for a longer, healthier life.',
    category: 'Health & Wellness',
    publishedDate: '2024-10-18',
  },
  {
    slug: 'understanding-chronological-age',
    title: 'Understanding Chronological Age: More Than Just a Number',
    description: 'Dive deep into what chronological age really means, how it differs from biological age, and why it remains a critical measure in our society. Learn the science behind calculating it accurately.',
    category: 'Core Concepts',
    publishedDate: '2024-10-15',
  },
   {
    slug: 'how-to-calculate-age-from-year-of-birth',
    title: 'How to Calculate Age From Year of Birth: The Simple Formula and Its Limits',
    description: 'Learn the quick and easy way to calculate age using just the year of birth. We explain the formula, when it’s useful, and why a full date of birth provides a more accurate result.',
    category: 'Core Concepts',
    publishedDate: '2024-10-16',
  },
  {
    slug: 'how-to-improve-biological-age',
    title: '5 Actionable Tips to Lower Your Biological Age',
    description: 'Your biological age is a better indicator of your health than your chronological age. Discover five evidence-based lifestyle changes you can make today to turn back the clock.',
    category: 'Health & Wellness',
    publishedDate: '2024-10-14',
  },
  {
    slug: 'what-generation-am-i',
    title: 'What Generation Am I? A Guide to Gen Z, Millennials, Gen X, and Boomers',
    description: 'Find out which generation you belong to with our easy-to-use chart. Learn the birth year cutoffs for Gen Z, Millennials, Gen X, and Baby Boomers.',
    category: 'Guides',
    publishedDate: '2024-10-13',
  },
  {
    slug: 'the-science-behind-pet-age-calculators',
    title: 'The Science Behind Dog and Cat Age Calculators',
    description: 'Is one dog year really equal to seven human years? We explore the modern science behind converting pet age to human years and why it matters for their health.',
    category: 'Pet Health',
    publishedDate: '2024-10-12',
  },
  {
    slug: 'planning-for-retirement-at-any-age',
    title: 'Planning for Retirement: A Decade-by-Decade Guide',
    description: 'Retirement planning looks different in your 20s than in your 50s. This guide breaks down the key steps you should be taking based on your current age.',
    category: 'Financial Planning',
    publishedDate: '2024-10-10',
  },
  {
    slug: 'navigating-pregnancy-milestones',
    title: 'Navigating Your Pregnancy: A Trimester-by-Trimester Milestone Guide',
    description: 'From the first positive test to the final countdown, understand the key milestones and developmental stages of your pregnancy journey.',
    category: 'Pregnancy',
    publishedDate: '2024-10-08',
  },
  {
    slug: 'what-is-chronological-age',
    title: 'What Is Chronological Age?',
    description: 'This article defines chronological age and explains its importance as the most common measure of how long a person has been alive.',
    category: 'Core Concepts',
    publishedDate: '2024-10-21',
  },
  {
    slug: 'how-to-tell-a-dogs-age',
    title: "How to Tell a Dog's Age: A Detective's Guide",
    description: 'Learn how to estimate a rescue or adopted dog\'s age by examining their teeth, eyes, coat, and energy level. A guide for curious pet owners.',
    category: 'Pet Health',
    publishedDate: '2024-10-22',
  },
  {
    slug: 'understanding-cat-life-stages',
    title: "Understanding Your Cat's Life Stages: From Kitten to Geriatric",
    description: 'A cat\'s needs change dramatically as they age. Learn about the six distinct life stages and how to provide the best care for each one.',
    category: 'Pet Health',
    publishedDate: '2024-10-23',
  },
  {
    slug: 'senior-dog-care-guide',
    title: "The Ultimate Guide to Caring for a Senior Dog",
    description: 'Ensure your senior dog\'s golden years are happy and comfortable. This guide covers nutrition, exercise, vet care, and enrichment for older dogs.',
    category: 'Pet Health',
    publishedDate: '2024-10-24',
  },
  {
    slug: 'common-health-problems-in-senior-cats',
    title: "5 Common Health Problems in Senior Cats: A Proactive Owner's Guide",
    description: 'Learn to recognize the subtle signs of the most common health issues in senior cats, including kidney disease, hyperthyroidism, and arthritis.',
    category: 'Pet Health',
    publishedDate: '2024-10-25',
  },
  {
    slug: 'puppy-development-milestones',
    title: "Your Puppy's First Year: A Milestone-by-Milestone Guide",
    description: "A puppy's first year is a whirlwind of change. Track their development from the neonatal period through their challenging adolescent phase.",
    category: 'Pet Health',
    publishedDate: '2024-10-26',
  },
  {
    slug: 'kitten-care-101',
    title: "Kitten Care 101: A Complete Guide for New Owners",
    description: 'Bringing home a new kitten? This guide covers the essentials of nutrition, socialization, vet care, and creating a safe environment for your new furball.',
    category: 'Pet Health',
    publishedDate: '2024-10-27',
  },
  {
    slug: 'why-small-dogs-live-longer',
    title: "Why Do Small Dogs Live Longer Than Large Dogs? The Biological Paradox",
    description: 'Explore the science behind why tiny Chihuahuas often outlive giant Great Danes, delving into theories about growth rates and cellular aging.',
    category: 'Pet Health',
    publishedDate: '2024-10-28',
  },
  {
    slug: 'choosing-the-right-dog-breed',
    title: "Choosing the Right Dog Breed for Your Lifestyle",
    description: 'Beyond cuteness: A practical guide to selecting a dog breed based on energy level, temperament, grooming needs, and living situation.',
    category: 'Pet Health',
    publishedDate: '2024-10-29',
  },
  {
    slug: 'introducing-a-new-cat',
    title: "How to Introduce a New Cat to Your Home: A Step-by-Step Guide",
    description: 'Ensure a peaceful transition when bringing a new cat into a home with existing pets. Follow this slow and steady method for a successful introduction.',
    category: 'Pet Health',
    publishedDate: '2024-10-30',
  },
  {
    slug: 'dog-vaccination-guide',
    title: "A Simple Guide to Your Dog's Vaccinations",
    description: 'Understand the difference between core and non-core (lifestyle) vaccines for your dog and why they are crucial for their long-term health.',
    category: 'Pet Health',
    publishedDate: '2024-11-01',
  },
  {
    slug: 'cat-vaccination-guide',
    title: "Your Cat's Vaccinations Explained: Core vs. Non-Core",
    description: 'Does your indoor cat really need shots? This guide explains the essential vaccines every cat needs and the optional ones based on their lifestyle.',
    category: 'Pet Health',
    publishedDate: '2024-11-02',
  },
  {
    slug: 'common-dog-health-problems',
    title: "5 Common Health Problems in Dogs (and Their Symptoms)",
    description: 'From ear infections to arthritis, learn to recognize the signs of the most common health issues that can affect dogs of all ages.',
    category: 'Pet Health',
    publishedDate: '2024-11-03',
  },
  {
    slug: 'your-pets-first-year',
    title: "Your Pet's First Year: A Guide for New Puppy and Kitten Owners",
    description: 'The first 12 months are crucial. This guide provides an overview of the key milestones and care requirements for new puppies and kittens.',
    category: 'Pet Health',
    publishedDate: '2024-11-04',
  },
  {
    slug: 'human-foods-toxic-to-pets',
    title: "10 Human Foods That Are Toxic to Dogs and Cats",
    description: 'Before you share your snack, read this list. A guide to common and dangerous human foods that should never be given to your pets.',
    category: 'Pet Health',
    publishedDate: '2024-11-05',
  },
  {
    slug: 'your-pet-s-first-vet-visit',
    title: "What to Expect at Your Pet's First Vet Visit",
    description: "A guide to navigating the crucial first veterinary appointment for your new puppy or kitten, from what to bring to what questions to ask.",
    category: 'Pet Health',
    publishedDate: '2024-11-06',
  },
];
