
[build]
  command = "next build"
  publish = ".next"

[build.environment]
  # Use a recent Long-Term Support (LTS) version of Node.js and npm
  NODE_VERSION = "20"
  NPM_VERSION = "10.5.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"
