
import RandomNumberGenerator from '@/components/calculators/random-number-generator';
import { type Metadata } from 'next';
import RelatedCalculators from '@/components/layout/related-calculators';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export const metadata: Metadata = {
    title: 'Random Number Generator – Integers & Decimals',
    description: 'A free online Random Number Generator for creating single or multiple random integers and decimals within a specified range and precision. Handles very large numbers.',
    alternates: {
        canonical: '/random-number-generator',
    },
};

export default function RandomNumberGeneratorPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="max-w-4xl mx-auto">
        <main role="main">
            <div className="text-center mb-8">
                <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-2">Random Number Generator</h1>
                <p className="text-md md:text-lg text-muted-foreground">
                    A versatile tool to generate random numbers, both integers and decimals, with support for very large numbers.
                </p>
            </div>

            <RandomNumberGenerator />

            <section className="mt-12 space-y-8 animate-fade-in prose dark:prose-invert lg:prose-xl max-w-none">
                <Card>
                    <CardHeader>
                        <CardTitle>How to Use the Random Number Generators</CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <div>
                            <h4 className="font-semibold text-foreground">Simple Random Integer Generator</h4>
                            <ol className="list-decimal list-inside space-y-2 text-muted-foreground mt-2">
                                <li><strong>Enter Limits:</strong> Input the desired lower and upper limits for your integer range. The upper limit must be greater than the lower limit.</li>
                                <li><strong>Click "Generate":</strong> A single random integer within your specified range will be displayed.</li>
                            </ol>
                        </div>
                        <div>
                            <h4 className="font-semibold text-foreground">Comprehensive Generator</h4>
                             <ol className="list-decimal list-inside space-y-2 text-muted-foreground mt-2">
                                <li><strong>Enter Limits:</strong> Input the lower and upper limits. This tool supports very large numbers.</li>
                                <li><strong>Set Quantity:</strong> Specify how many random numbers you want to generate (up to 100).</li>
                                <li><strong>Choose Type:</strong> Select whether you want 'Integer' or 'Decimal' results.</li>
                                <li><strong>Set Precision:</strong> For decimals, define the number of significant digits for high precision.</li>
                                <li><strong>Click "Generate":</strong> A list of your specified random numbers will appear in the results box.</li>
                            </ol>
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader>
                        <CardTitle>Understanding Random Numbers</CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4 text-muted-foreground">
                        <p>A random number is a number chosen from a pool of limited or unlimited numbers that has no discernible pattern for prediction. The pool of numbers is almost always independent from each other. However, the pool of numbers may follow a specific distribution. For example, the height of the students in a school tends to follow a normal distribution around the median height. If the height of a student is picked at random, the picked number has a higher chance to be closer to the median height than being classified as very tall or very short. The random number generators above assume that the numbers generated are independent of each other, and will be evenly spread across the whole range of possible values.</p>
                        <p>A random number generator, like the ones above, is a device that can generate one or many random numbers within a defined scope. Random number generators can be hardware based or pseudo-random number generators. Hardware based random-number generators can involve the use of a dice, a coin for flipping, or many other devices.</p>
                        <p>A pseudo-random number generator is an algorithm for generating a sequence of numbers whose properties approximate the properties of sequences of random numbers. Computer based random number generators are almost always pseudo-random number generators. Yet, the numbers generated by pseudo-random number generators are not truly random. Likewise, our generators above are also pseudo-random number generators. The random numbers generated are sufficient for most applications yet they should not be used for cryptographic purposes. True random numbers are based on physical phenomena such as atmospheric noise, thermal noise, and other quantum phenomena. Methods that generate true random numbers also involve compensating for potential biases caused by the measurement process.</p>
                    </CardContent>
                </Card>
            </section>
        </main>
        <RelatedCalculators currentCategory="Math Calculators" currentHref="/random-number-generator" />
      </div>
    </div>
  );
}
