
import InterestRateCalculator from '@/components/calculators/interest-rate-calculator';
import { type Metadata } from 'next';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import RelatedCalculators from '@/components/layout/related-calculators';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import Link from 'next/link';

export const metadata: Metadata = {
    title: 'Interest Rate Calculator – Find Loan APR from Payments',
    description: 'Use our free Interest Rate Calculator to find the actual APR of a loan. Enter the loan amount, term, and monthly payment to solve for the interest rate.',
    alternates: {
        canonical: '/interest-rate-calculator',
    },
};

const faqs = [
    {
        question: "How do you calculate the interest rate on a loan?",
        answer: "Calculating the interest rate from loan payments requires solving the loan amortization formula for the rate, which usually requires an iterative numerical method. Our calculator automates this complex process for you."
    },
    {
        question: "Why would I need to calculate an interest rate?",
        answer: "This tool is very useful in situations where you are given a loan offer with a monthly payment amount but the interest rate (APR) is not clearly disclosed, which can sometimes happen at car dealerships."
    },
    {
        question: "What is APR?",
        answer: "APR stands for Annual Percentage Rate. It is the yearly interest generated by a sum that's charged to borrowers or paid to investors. It includes any fees or additional costs associated with the transaction, though this calculator solves for the simple interest rate based on the loan amount provided."
    },
    {
        question: "Is this calculator accurate?",
        answer: "This calculator provides a very accurate mathematical result for the nominal interest rate based on the values you enter. However, it does not account for additional fees that may be part of a loan's APR. It's an excellent tool for estimation and comparison."
    }
];

const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": faqs.map(faq => ({
        "@type": "Question",
        "name": faq.question,
        "acceptedAnswer": {
            "@type": "Answer",
            "text": faq.answer
        }
    }))
};

export default function InterestRateCalculatorPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <div className="max-w-4xl mx-auto">
        <main role="main">
            <div className="text-center mb-8">
                <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-2">Interest Rate Calculator</h1>
                <p className="text-md md:text-lg text-muted-foreground">
                    Determine the implied interest rate (APR) of a loan when you know the loan amount, term, and monthly payment.
                </p>
            </div>

            <InterestRateCalculator />

            <section className="mt-12 space-y-8 animate-fade-in">
                <Card>
                    <CardHeader>
                        <CardTitle>Learn More About Loans</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                            <li><Link href="/articles/understanding-your-credit-score" className="text-primary hover:underline">Understanding Your Credit Score</Link></li>
                        </ul>
                    </CardContent>
                </Card>
                <Card>
                    <CardHeader>
                        <CardTitle>How to Use the Interest Rate Calculator</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <ol className="list-decimal list-inside space-y-2 text-muted-foreground">
                            <li><strong>Loan Amount:</strong> Enter the total amount you are borrowing.</li>
                            <li><strong>Loan Term:</strong> Input the total length of the loan in years and/or months.</li>
                            <li><strong>Monthly Payment:</strong> Provide the fixed monthly payment amount for the loan.</li>
                            <li><strong>Click “Calculate Rate”:</strong> Instantly receive the calculated annual interest rate and a summary of your loan's cost.</li>
                        </ol>
                    </CardContent>
                </Card>

                <div>
                    <h2 className="text-2xl md:text-3xl font-bold mb-4">Frequently Asked Questions</h2>
                    <Accordion type="single" collapsible className="w-full">
                        {faqs.map((faq, index) => (
                             <AccordionItem value={`item-${index}`} key={index}>
                                <AccordionTrigger>{faq.question}</AccordionTrigger>
                                <AccordionContent>
                                    <p>{faq.answer}</p>
                                </AccordionContent>
                            </AccordionItem>
                        ))}
                    </Accordion>
                </div>
            </section>
        </main>
        <RelatedCalculators currentCategory="Financial Calculators" currentHref="/interest-rate-calculator" />
      </div>
    </div>
  );
}
